import './globals.css'
import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {

  return (
    <html lang="en">
      <body>
        <div className='container'>
        {/* <MainLayout children={children}/> */}
        {children}
        </div>
      </body>
    </html>
  )
}
